stages:
  - build
  - pages

publish:

  stage: pages

  image: registry.gitlab.com/contentascode/activist-apprentice:v0.0.9

  cache:
    paths:
    - node_modules/

  before_script:
  - mkdir workspace && cd workspace
  - apprentice init --non-interactive
  - apprentice config
  # Manually template with current course
  - rm -rf ~/.content/packages/activist-apprentice-course-template
  - cp -R $CI_PROJECT_DIR ~/.content/packages/activist-apprentice-course-template
  - cd ~/.content/packages/activist-apprentice-course-template
  - npm install


  script:
  # Build website
  - cd $CI_PROJECT_DIR/workspace
  - apprentice start --clean --no-watch --baseurl /activist-apprentice/@apprentice/preview
  - cd ~/.content/build/@apprentice/mobile
  - npm install
  - npm install -g exp
  - exp login -u $EXP_LOGIN -p $EXP_PASS
  - exp publish --non-interactive
  - cp -R $HOME/.content/build public
  - ls -la public

  artifacts:
    paths:
    - public

  only:
    - master
